Feat: #1202: Updating user service documentation
1-Platform/one-platform pull request #1009
Opened 2021-06-29 17:57 UTC by ghanlohar

# Closes/Fixes/Resolves

### 
ONEPLAT-1202
# Explain the feature/fix

Updating user service documentation as per the latest implementation of Rover integration.

## Does this PR introduce a breaking change

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2021-06-29 19:43 UTC, riginoommen approved these changes

2021-07-05 07:40 UTC, hybridx requested changes

2021-07-05 07:40 UTC, hybridx commented on packages/documentation-spa/docs/microservices/user-groups/user-groups-service.md
> +3. ### Search Users based on a criteria from Rover and optionally cache them into the cache DB.
```suggestion
3. ### Search Users based on a criteria from Rover and optionally cache them into the cache DB.
```
@ghanlohar can you add a s/c for this?
the `3. ###` might not work together

2021-07-05 07:40 UTC, hybridx commented on packages/documentation-spa/docs/microservices/user-groups/user-groups-service.md
> +4. ### Fetch group details & members included in a Rover group
@ghanlohar Same as above

2021-07-05 07:40 UTC, hybridx commented on packages/documentation-spa/docs/microservices/user-groups/user-groups-service.md
> +2. ### Add new user from Rover
@ghanlohar same as above

2021-07-05 08:00 UTC, hybridx approved these changes

2021-07-05 08:54 UTC, merged