(docs/apps): Adds documentation for App Service and some permalink changes for other docs
1-Platform/one-platform pull request #1012
Opened 2021-07-07 13:24 UTC by deshmukhmayur

# Closes 1205

# Explain the feature/fix

## Does this PR introduce a breaking change

Yes. Some of the permalink to the documentation from other SPAs might be broken. I've tried to fix it wherever I could find the old links in home spa and user-group spa.

Need to check if any other SPA requires these changes.

## Screenshots

<details>
<summary>View Screenshots</summary>

| Label | Screenshot |
|---|---|
| Sidebar reordered | <img width="301" alt="Screenshot 2021-07-07 at 6 51 30 PM" src="https://user-images.githubusercontent.com/19623278/124766306-6df5bc00-df54-11eb-9e96-0c2d72a42d9a.png"> |
| Deprecation notice on Home Service | <img width="1364" alt="Screenshot 2021-07-07 at 6 50 37 PM" src="https://user-images.githubusercontent.com/19623278/124766450-9087d500-df54-11eb-96b8-7a2cd1b5405f.png"> |
| Apps Service Documentation | <img width="974" alt="Screenshot 2021-07-07 at 6 53 34 PM" src="https://user-images.githubusercontent.com/19623278/124766534-a4cbd200-df54-11eb-88d4-eb30f400dcca.png"> |

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?

2021-07-07 15:18 UTC, hybridx approved these changes
Home-SPA changes look good along with other changes

2021-07-07 17:42 UTC, riginoommen requested changes

2021-07-07 17:42 UTC, riginoommen commented on packages/documentation-spa/blog/2020-08-18-announcing-one-platform-beta.md
> +- Enhancements to the [User & Group microservice](https://beta.one.redhat.com/get-started/docs/microservices/user-groups-service/) for implementing a consolidated team framework.
```suggestion
- Enhancements to the [User & Group microservice](https://one.redhat.com/get-started/docs/microservices/user-groups-service/) for implementing a consolidated team framework.
```

2021-07-07 17:42 UTC, riginoommen commented on packages/documentation-spa/blog/2020-08-18-announcing-one-platform-beta.md
>  - Enhancements to the [Home page](https://beta.one.redhat.com/) for seamless user experience.
```suggestion
- Enhancements to the [Home page](https://one.redhat.com/) for seamless user experience.
```

2021-07-07 17:42 UTC, riginoommen commented on packages/documentation-spa/blog/2020-08-18-announcing-one-platform-beta.md
>  - One Portal Migration: Complete [MoD Handovers](https://beta.one.redhat.com/mod-handovers/) SPA Beta UI release.
```suggestion
- One Portal Migration: Complete [MoD Handovers](https://one.redhat.com/mod-handovers/) SPA Beta UI release.
```

2021-07-07 17:42 UTC, riginoommen commented on packages/documentation-spa/blog/2020-08-18-announcing-one-platform-beta.md
>  - Analyst Papers SPA: [Beta UI](https://beta.one.redhat.com/analyst-papers) release that includes Listing, Search, Quote, Quick Preview and Google Drive integration.
```suggestion
- Analyst Papers SPA: [Beta UI](https://one.redhat.com/analyst-papers) release that includes Listing, Search, Quote, Quick Preview and Google Drive integration.
```

2021-07-08 04:06 UTC, riginoommen commented on packages/documentation-spa/docs/microservices/apps-service/app-service.md
> +Apps Servicee is the indexing service which allows you to create and manage individual apps/projects on One Platform. It provides CRUD operations for the app metadata.
```suggestion
Apps Service is the indexing service which allows you to create and manage individual apps/projects on One Platform. It provides CRUD operations for the app metadata.
```

2021-07-08 07:35 UTC, deshmukhmayur commented on packages/documentation-spa/docs/microservices/apps-service/app-service.md
> +Apps Servicee is the indexing service which allows you to create and manage individual apps/projects on One Platform. It provides CRUD operations for the app metadata.
Fixed. Thanks for pointing it out.

2021-07-08 07:36 UTC, riginoommen approved these changes

2021-07-08 12:42 UTC, merged