Feat#1287: Improving the search index API & API helper modifications in Feedback service
1-Platform/one-platform pull request #1016
Opened 2021-07-09 20:46 UTC by ghanlohar

# Closes/Fixes/Resolves
ONEPLAT-1287
### 

# Explain the feature/fix

- Improving the search index API 
- Search API helper modifications in Feedback service

## Does this PR introduce a breaking change
Yes

## Screenshots

<details>
<summary>View Screenshots</summary>

<img width="1433" alt="Screenshot 2021-07-10 at 2 14 28 AM" src="https://user-images.githubusercontent.com/5575651/125134177-9fbd7d00-e124-11eb-9bbe-c5da58cf8b49.png">

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2021-07-10 16:25 UTC, riginoommen requested changes

2021-07-10 16:25 UTC, riginoommen commented on packages/search-service/src/search-config/typedef.graphql
> +  manageIndex(input: SearchInput, mode: String): SearchResponseCode
```suggestion
  manageIndex(input: SearchInput, mode: String!): SearchResponseCode
```

2021-07-10 16:25 UTC, riginoommen commented on packages/search-service/src/search-mapping/resolver.ts
> +            return "Indexing Search Maps has been triggered.";
```suggestion
            return 'Indexing Search Maps has been triggered.';
```

2021-07-10 16:25 UTC, riginoommen commented on packages/feedback-service/src/helpers.ts
> +                    input: mode === "index"? data?.input : data,
```suggestion
                    input: mode === 'index'? data?.input : data,
```

2021-07-10 16:25 UTC, riginoommen commented on packages/feedback-service/src/helpers.ts
>                      console.log("Error in index updation.");
```suggestion
                    console.info('Error in index updation.');
```

2021-07-10 16:25 UTC, riginoommen commented on packages/feedback-service/src/helpers.ts
>                      console.log('Sucessfully completed the index updation')
```suggestion
                    console.info('Sucessfully completed the index updation')
```

2021-07-10 16:25 UTC, riginoommen commented on packages/feedback-service/src/helpers.ts
> +                    'tags': `Feedback, ${data?.category},`,
```suggestion
                    'tags': `Feedback, ${data?.category}`,
```

2021-07-12 06:49 UTC, ghanlohar commented on packages/feedback-service/src/helpers.ts
> +                    input: mode === "index"? data?.input : data,
Done

2021-07-12 06:49 UTC, ghanlohar commented on packages/search-service/src/search-config/typedef.graphql
> +  manageIndex(input: SearchInput, mode: String): SearchResponseCode
Done

2021-07-12 06:49 UTC, ghanlohar commented on packages/search-service/src/search-mapping/resolver.ts
> +            return "Indexing Search Maps has been triggered.";
Done

2021-07-12 06:49 UTC, ghanlohar commented on packages/feedback-service/src/helpers.ts
>                      console.log("Error in index updation.");
Done

2021-07-12 06:50 UTC, ghanlohar commented on packages/feedback-service/src/helpers.ts
>                      console.log('Sucessfully completed the index updation')
Done

2021-07-12 06:50 UTC, ghanlohar commented on packages/feedback-service/src/helpers.ts
> +                    'tags': `Feedback, ${data?.category},`,
Done

2021-07-12 07:03 UTC, riginoommen approved these changes

2021-07-13 07:15 UTC, deshmukhmayur approved these changes

2021-07-13 07:16 UTC, merged