Batching & retry the index operation for search service.
1-Platform/one-platform pull request #1038
Opened 2021-07-22 18:05 UTC by ghanlohar

ONEPLAT-1304
# Closes/Fixes/Resolves

### 

# Explain the feature/fix

- Implemented batching and retry for the indexing of the search data

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2021-07-23 05:27 UTC, riginoommen requested changes

2021-07-23 05:27 UTC, riginoommen commented on packages/search-service/src/search-mapping/cron.ts
> +                    dataSource: "oneportal",
```suggestion
                    dataSource: process.env.SEARCH_DATA_SOURCE,
```

2021-07-23 11:11 UTC, deshmukhmayur approved these changes
Other than the change requested by @riginoommen, the rest looks good.

2021-07-26 07:30 UTC, riginoommen approved these changes

2021-07-26 07:31 UTC, merged