(Fix:lh-image) - Included non-root permission for the image
1-Platform/one-platform pull request #1039
Opened 2021-07-23 05:42 UTC by riginoommen

# Explain the fix
Included the non-root permission for the image.

## Does this PR introduce a breaking change
No

## Screenshots
N/A

### Ready-for-merge Checklist
- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?

2021-07-23 11:10 UTC, deshmukhmayur requested changes

2021-07-23 11:10 UTC, deshmukhmayur commented on packages/lighthouse-service/Dockerfile
> +USER 1001
```suggestion
USER 1001

CMD [ "node", "dist/bundle.js"]
```

2021-07-23 15:45 UTC, riginoommen commented on packages/lighthouse-service/Dockerfile
> +USER 1001
Updated

2021-07-26 16:56 UTC, ghanlohar approved these changes

2021-07-27 05:58 UTC, deshmukhmayur approved these changes

2021-07-27 05:59 UTC, deshmukhmayur requested changes
@riginoommen Can you edit the commit message?
The commit message does not seem to correspond with the change.

2021-07-27 06:06 UTC, deshmukhmayur approved these changes

2021-07-27 06:06 UTC, merged