Feat/lighthouse UI
1-Platform/one-platform pull request #1057
Opened 2021-08-02 08:47 UTC by akhilmhdh

# Closes/Fixes/Resolves

1370

# Explain the feature/fix

1. Implement ui changes in lighthouse SPA
2. Fixed broken unit tests of angular

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

![Screenshot 2021-08-02 at 2 09 53 PM](https://user-images.githubusercontent.com/31166322/127832058-44930998-754a-4f69-876c-f7b48231f544.png)

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2021-08-02 10:58 UTC, ghanlohar approved these changes
LGTM

2021-08-03 04:46 UTC, riginoommen commented on packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html
> +                            one-portal-devel@redhat.com
Make this as an env variable

2021-08-03 04:47 UTC, riginoommen requested changes

2021-08-03 04:47 UTC, riginoommen commented on packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.ts
> +    // this.router.navigateByUrl(`/?site_url=${this.sites}`);
```suggestion
```

2021-08-03 06:32 UTC, akhilmhdh commented on packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.ts
> +    // this.router.navigateByUrl(`/?site_url=${this.sites}`);
Done

2021-08-03 06:34 UTC, akhilmhdh commented on packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html
> +                            one-portal-devel@redhat.com
Done

2021-08-03 14:13 UTC, riginoommen approved these changes

2021-08-04 04:40 UTC, merged