(fix:1576) - Upgraded the user group microservice with latest dependencies
1-Platform/one-platform pull request #1291
Opened 2021-11-08 16:34 UTC by riginoommen

# Resolves 1576

# Explain the change

Upgraded the user group microservice with latest dependencies

## Does this PR introduce a breaking change

Yes

- Included morgan logging
- updated test case configurations
- Upgraded the graphql and dependencies
- Included the universal logging with winston

## Screenshots
<details>
<summary>View Screenshots</summary>

- Test status
![image](https://user-images.githubusercontent.com/3840244/140780477-3bb2553c-8d36-4b61-be30-f6448092d0cc.png)

- Studio Interface
![image](https://user-images.githubusercontent.com/3840244/140780662-a1ef0a86-b7de-44a5-a1fb-1c7f6e6233df.png)

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2021-11-09 08:03 UTC, ghanlohar requested changes

2021-11-09 09:16 UTC, riginoommen commented on packages/user-group-service/package.json
> +  "version": "0.0.3-beta",
Yes because 0 0 2 is the version you made with rover 0.0.3 is the new upgrade

2021-11-09 09:56 UTC, ghanlohar commented on packages/user-group-service/package.json
> +  "version": "0.0.3-beta",
OK. That makes sense.

2021-11-09 09:56 UTC, ghanlohar approved these changes

2021-11-17 08:15 UTC, deshmukhmayur approved these changes

2021-11-17 08:16 UTC, merged