test for search,edit and delete of apis(ONEPLAT-1724)
1-Platform/one-platform pull request #1334
Opened 2021-12-07 15:10 UTC by mudit94

# Closes/Fixes/Resolves

### 

# Explain the feature/fix

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2021-12-07 15:23 UTC, riginoommen requested changes

2021-12-07 15:23 UTC, riginoommen commented on e2e/integration/apicatalogtests.js
> +let words;
```suggestion
```

2021-12-07 15:23 UTC, riginoommen commented on e2e/integration/apicatalogtests.js
> +        //this.words=words
```suggestion
```

2021-12-07 15:23 UTC, riginoommen commented on e2e/integration/apicatalogtests.js
> +        //cy.get( 'input[name="name"]' ).invoke('text').as('wordID')
```suggestion
```

2021-12-07 15:23 UTC, riginoommen commented on e2e/integration/searchtests.js
> +        //cy.get( 'op-nav' ).find( 'input[name="query"]' ).click( { force: true } ).clear( { force: true } ).type( 'qwertyuiopasdgthchgbtnjkmnvxs', { force: true } );
```suggestion
```

2021-12-07 16:03 UTC, mudit94 commented on e2e/integration/apicatalogtests.js
> +let words;
resolved @riginoommen  https://github.com/1-Platform/one-platform/pull/1334/commits/579d9b4f9295f5fa94d2610890cf2007f2ebc0c4

2021-12-07 16:03 UTC, mudit94 commented on e2e/integration/searchtests.js
> +        //cy.get( 'op-nav' ).find( 'input[name="query"]' ).click( { force: true } ).clear( { force: true } ).type( 'qwertyuiopasdgthchgbtnjkmnvxs', { force: true } );
https://github.com/1-Platform/one-platform/pull/1334/commits/579d9b4f9295f5fa94d2610890cf2007f2ebc0c4 resolved @riginoommen

2021-12-07 16:04 UTC, mudit94 commented on e2e/integration/apicatalogtests.js
> +        //cy.get( 'input[name="name"]' ).invoke('text').as('wordID')
https://github.com/1-Platform/one-platform/pull/1334/commits/579d9b4f9295f5fa94d2610890cf2007f2ebc0c4 resolved @riginoommen

2021-12-07 16:04 UTC, mudit94 commented on e2e/integration/apicatalogtests.js
> +        //this.words=words
resolved @riginoommen https://github.com/1-Platform/one-platform/pull/1334/commits/579d9b4f9295f5fa94d2610890cf2007f2ebc0c4

2021-12-08 05:04 UTC, hybridx approved these changes

2021-12-09 09:34 UTC, hybridx approved these changes

2021-12-10 05:25 UTC, mudit94 commented on e2e/integration/searchtests.js
> +        //cy.get( 'op-nav' ).find( 'input[name="query"]' ).click( { force: true } ).clear( { force: true } ).type( 'qwertyuiopasdgthchgbtnjkmnvxs', { force: true } );
https://github.com/1-Platform/one-platform/pull/1334/commits/be6e9afef069a3aed36f8a7926bc6a2a1f90fb27 resolved @riginoommen

2021-12-13 05:24 UTC, riginoommen approved these changes

2021-12-13 05:27 UTC, riginoommen commented
SQUASH the commits

2021-12-13 11:58 UTC, merged