feat:1811 - Integrated the EXD Catalog with the API catalog
1-Platform/one-platform pull request #1422
Opened 2022-01-28 12:22 UTC by riginoommen

# Resolves 1811

# Explain the feature
Integrated the EXD Catalog with the API catalog

## Does this PR introduce a breaking change

No
`
## Screenshots

<details>
<summary>View Screenshots</summary>

![image](https://user-images.githubusercontent.com/3840244/151546006-7ad57c2c-a60c-4df8-bc27-45bdc78bd96d.png)
</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2022-01-28 15:57 UTC, akhilmhdh requested changes
Bump up the version number please

2022-01-28 16:07 UTC, riginoommen commented
Done the version bump

2022-01-28 16:08 UTC, akhilmhdh approved these changes

2022-01-31 07:08 UTC, gisumit approved these changes

2022-01-31 08:33 UTC, hybridx approved these changes

2022-01-31 08:33 UTC, merged