feat(dev-console): added feedback spa link in feedback list page
1-Platform/one-platform pull request #1449
Opened 2022-02-09 06:53 UTC by akhilmhdh

# Fix

# Explain the feature/fix

1. Added feedback spa link to feedback list page in dev console
2. Truncated summary in table to 200 characters
3. Added color change for bug in list view

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

## Feedback List

![Screenshot 2022-02-09 at 12 00 43 PM](https://user-images.githubusercontent.com/31166322/153137290-2e6b9d52-f91b-4bdf-a54f-c1bec21ed7e5.png)

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demoed and the design review approved?

2022-02-09 07:05 UTC, riginoommen requested changes
Quotes selections should be consistent

2022-02-09 07:05 UTC, riginoommen commented on packages/developer-console-spa/src/components/feedback/FeedbackList.tsx
> +    toString: () => "Sort by: newest",
```suggestion
    value: "CREATED_ON",
    toString: () => 'Sort by: newest',
```

2022-02-09 07:05 UTC, riginoommen commented on packages/developer-console-spa/src/components/feedback/FeedbackList.tsx
> +    value: "CREATED_ON",
```suggestion
    value: 'CREATED_ON',
```

2022-02-09 07:05 UTC, riginoommen commented on packages/developer-console-spa/src/components/feedback/FeedbackList.tsx
> +    toString: () => "Sort by: activity",
```suggestion
    value: 'UPDATED_ON',
    toString: () => 'Sort by: activity',
```

2022-02-09 07:05 UTC, riginoommen commented on packages/developer-console-spa/src/components/feedback/FeedbackList.tsx
> +    (text: string) => (text.length > 200 ? text.slice(0, 200) + "..." : text),
```suggestion
    (text: string) => (text.length > 200 ? text.slice(0, 200) + '...' : text),
```

2022-02-09 07:25 UTC, akhilmhdh commented
@riginoommen Sorry about that. But its a vscode issue. We are having so much collision going on in linting.

There is editor.config, vs code workspace, then another set of base eslint and prettier issues.

But yah fixed it

2022-02-10 15:12 UTC, riginoommen approved these changes

2022-02-11 07:33 UTC, ghanlohar approved these changes
LGTM

2022-02-14 06:42 UTC, deshmukhmayur approved these changes

2022-02-14 06:43 UTC, merged