test(e2e): added the automation tests for error page
1-Platform/one-platform pull request #1550
Opened 2022-05-12 07:42 UTC by mudit94

# Closes/Fixes/Resolves

### 

# Explain the feature/fix

test(e2e): added the automation tests for error page
## Does this PR introduce a breaking change

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- Test are not passing as the data  in the application is incorrect(the links are not pointing to correct urls)
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demoed and the design review approved?

2022-05-13 06:23 UTC, riginoommen requested changes

2022-05-13 06:23 UTC, riginoommen commented on e2e/integration/errorpagetests.js
> +        cy.contains( 'Documentation' ).should( 'be.visible' ).should( 'have.attr', 'href', 'https://qa.one.redhat.com/get-started' );
```suggestion
        cy.contains( 'Documentation' ).should( 'be.visible' ).should( 'have.attr', 'href', 'https://qa.one.redhat.com/get-started' );
```
use QA_HOST variable

2022-05-13 06:23 UTC, riginoommen commented on e2e/integration/errorpagetests.js
> +        cy.contains( 'Feedback' ).should( 'be.visible' ).should( 'have.attr', 'href', 'https://qa.one.redhat.com/feedback' );
use QA_HOST variable

2022-05-13 06:23 UTC, riginoommen commented on e2e/integration/errorpagetests.js
> +        cy.contains( 'Notifications' ).should( 'be.visible' ).should( 'have.attr', 'href', 'https://qa.one.redhat.com/notifications' );
use QA_HOST variable

2022-05-13 06:23 UTC, riginoommen commented on e2e/integration/errorpagetests.js
> +        cy.contains( 'User Group' ).should( 'have.attr', 'href', 'https://qa.one.redhat.com/user-groups' );
use QA_HOST variable

2022-05-13 06:40 UTC, mudit94 commented on e2e/integration/errorpagetests.js
> +        cy.contains( 'Documentation' ).should( 'be.visible' ).should( 'have.attr', 'href', 'https://qa.one.redhat.com/get-started' );
fixed

2022-05-13 06:40 UTC, mudit94 commented on e2e/integration/errorpagetests.js
> +        cy.contains( 'User Group' ).should( 'have.attr', 'href', 'https://qa.one.redhat.com/user-groups' );
this has been fixed

2022-05-13 06:41 UTC, mudit94 commented on e2e/integration/errorpagetests.js
> +        cy.contains( 'Feedback' ).should( 'be.visible' ).should( 'have.attr', 'href', 'https://qa.one.redhat.com/feedback' );
fixed

2022-05-13 07:45 UTC, riginoommen approved these changes

2022-05-13 08:00 UTC, hybridx approved these changes
LGTM

2022-05-16 06:06 UTC, riginoommen approved these changes

2022-05-16 06:06 UTC, merged