1417 - Updated the search to the New UI
1-Platform/one-platform pull request #1564
Opened 2022-06-02 09:36 UTC by riginoommen

# Resolves 1417

# Explain the feature
Updated the Search UI to the latest specification.

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

<img width="1790" alt="Screenshot 2022-06-02 at 3 00 13 PM" src="https://user-images.githubusercontent.com/3840244/171601035-e51ee98b-ad2a-479b-a59b-b7418e8d9fea.png">
<img width="1790" alt="Screenshot 2022-06-02 at 3 00 31 PM" src="https://user-images.githubusercontent.com/3840244/171601056-846603db-bbd5-4fe1-99e0-4e4c86eceeaa.png">

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demoed and the design review approved?

2022-06-03 06:08 UTC, deshmukhmayur approved these changes

2022-06-06 04:59 UTC, akhilmhdh requested changes
Lastly. Don't you think server side pagination will be better than client side

2022-06-06 04:59 UTC, akhilmhdh commented on packages/search-spa/src/app/search/search.component.ts
> +import groupBy from 'lodash/groupBy';
Is this `groupBy` and `map` used. I didn't find any reference

2022-06-06 06:08 UTC, akhilmhdh approved these changes

2022-06-06 06:08 UTC, akhilmhdh commented
Server side pagination it is

2022-06-06 06:08 UTC, merged