feat: revamped doc spa
1-Platform/one-platform pull request #1571
Opened 2022-06-16 12:40 UTC by akhilmhdh

# Fixes

# Explain the feature/fix

1. Revamped doc spa and its content
2. Fixed opc-base reloading bug in firefox that happens sometimes
3. Blog listing fixed

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

## Blog Listing

![Screenshot 2022-06-16 at 6 06 32 PM](https://user-images.githubusercontent.com/31166322/174071526-9b5dc98c-f19c-423c-9986-87d12e4e990b.png)

## Doc Page

![Screenshot 2022-06-16 at 6 06 16 PM](https://user-images.githubusercontent.com/31166322/174071550-d92af9c6-c863-4252-920a-dcede865c062.png)

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demoed and the design review approved?

2022-06-16 12:57 UTC, riginoommen approved these changes

2022-06-16 13:00 UTC, riginoommen requested changes
Just remove unused variable

2022-06-20 06:16 UTC, akhilmhdh commented on packages/doc-spa/blog/2021-04-12-state-of-one-platform-mar-2021.md
> +tags: [redhat, blog, oneportal, oneplatform, react, angular, january, update]
Resolved

2022-06-20 06:17 UTC, akhilmhdh commented on packages/doc-spa/blog/2021-03-10-state-of-one-platform-feb-2021.md
> +tags: [redhat, blog, oneportal, oneplatform, react, angular, january, update]
Resolved

2022-06-22 08:54 UTC, riginoommen approved these changes

2022-06-28 05:33 UTC, riginoommen approved these changes

2022-06-28 05:36 UTC, merged