#2147 - Implemented the Data Export Option for Lighthouse SPA
1-Platform/one-platform pull request #1573
Opened 2022-06-23 07:19 UTC by riginoommen

# Resolves 2147

# Explain the feature

Implemented Data Export Option for Lighthouse SPA and Microservice

## Does this PR introduce a breaking change

No

## Screenshots
<details>
- Created button in UI for csv download

<summary>View Screenshots</summary>

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3840244/175235410-5ba5c5ed-aad6-47bc-b77c-c5012ca74d1d.png">
</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demoed and the design review approved?

2022-06-28 08:20 UTC, deshmukhmayur approved these changes

2022-06-28 11:46 UTC, akhilmhdh requested changes
Kindly write the testcase for this LH functionality

2022-06-28 11:46 UTC, akhilmhdh commented on packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
> +    this.dashboardService.exportLHReportByProject( this.projectId, this.selectedBranch ).subscribe( data => {
Remove the subscription on unmount by passing the destroying sub

2022-07-18 06:34 UTC, deshmukhmayur approved these changes
@riginoommen Is this ready for merging?

2022-07-25 05:47 UTC, hybridx approved these changes
LGTM

2022-07-25 05:49 UTC, merged