chore(1602-fix) - Setting size as 4096
1-Platform/one-platform pull request #1604
Opened 2022-09-01 07:00 UTC by hybridx

# Closes/Fixes/Resolves

### Resolves #1602

2022-09-01 19:06 UTC, riginoommen requested changes

2022-09-01 19:06 UTC, riginoommen commented on packages/lighthouse-spa/src/environments/environment.prod.ts
> +   SENTRY_DSN: undefined,
Please remove this values

2022-09-01 19:06 UTC, riginoommen commented on packages/search-spa/src/environments/environment.prod.ts
> +   SENTRY_DSN: undefined,
Please remove this value

2022-09-02 05:43 UTC, hybridx commented on packages/lighthouse-spa/src/environments/environment.prod.ts
> +   SENTRY_DSN: undefined,
Got it, Thanks

2022-09-02 05:44 UTC, hybridx commented on packages/search-spa/src/environments/environment.prod.ts
> +   SENTRY_DSN: undefined,
Got it, Thanks

2022-09-02 06:46 UTC, riginoommen submitted a review, later dismissed

2022-09-06 06:21 UTC, riginoommen approved these changes

2022-09-14 16:40 UTC, riginoommen approved these changes

2022-09-16 03:34 UTC, riginoommen submitted a review, later dismissed

2022-09-16 03:41 UTC, hybridx commented
Support for web-test-runner to be added later with nx cloud or self hosted runner

2022-09-16 04:03 UTC, deshmukhmayur approved these changes

2022-09-16 04:04 UTC, deshmukhmayur requested changes
@hybridx can you clean up the commits?
Merge them into logical commits.

2022-09-16 04:10 UTC, hybridx commented
> @hybridx can you clean up the commits? Merge them into logical commits.

@deshmukhmayur I think that we can squash these commits, they are changes to only CI/CD mainly

2022-09-16 06:26 UTC, deshmukhmayur approved these changes

2022-09-16 06:54 UTC, riginoommen approved these changes

2022-09-16 06:54 UTC, merged