fix:2215 - Fixed tha validation for lighthouse urls
1-Platform/one-platform pull request #1607
Opened 2022-09-12 06:24 UTC by riginoommen

# Fixes

### 

# Explain the fix 2215

Fixed the URL validation issues for the lighthouse spa
## Does this PR introduce a breaking change

No

## Screenshots
<details>
<summary>View Screenshots</summary>

<img width="783" alt="image" src="https://user-images.githubusercontent.com/3840244/189586566-10f9deb7-b12f-4c75-9a54-98821a714e2b.png">
<img width="710" alt="image" src="https://user-images.githubusercontent.com/3840244/189586598-e912efdb-2573-4425-80a7-97dea7aa88a8.png">
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/3840244/189586677-80e71293-a65b-4062-9645-41121037d259.png">

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?

2022-09-15 12:10 UTC, riginoommen commented
Fixed the above alerts

2022-09-15 12:22 UTC, deshmukhmayur requested changes

2022-09-15 12:22 UTC, deshmukhmayur commented on packages/lighthouse-spa/src/app/shared/directive/url-validator.directive.ts
> +        if (yup.string().url().isValidSync(url) === true) {
```suggestion
        if (yup.string().url().isValidSync(url)) {
```

2022-09-15 12:26 UTC, riginoommen commented on packages/lighthouse-spa/src/app/shared/directive/url-validator.directive.ts
> +        if (yup.string().url().isValidSync(url) === true) {
Updated

2022-09-15 12:44 UTC, deshmukhmayur approved these changes

2022-09-16 06:54 UTC, hybridx submitted a review, later dismissed

2022-09-19 06:07 UTC, riginoommen commented
Rebased the PR and fixed the conflicts

2022-09-19 06:18 UTC, merged