feat(2245): implemented user analytics with matomo
1-Platform/one-platform pull request #1635
Opened 2022-10-06 15:57 UTC by akhilmhdh

# Closes

1. 2245

# Explain the feature/fix

1. Implemented  user analytics in analytics service
2. Integrated with matomo
3. Changed sentry crashlytics api

## Does this PR introduce a breaking change

Yes

Changed crashlytics API

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demoed and the design review approved?

2022-10-07 07:35 UTC, riginoommen requested changes

2022-10-10 04:17 UTC, akhilmhdh commented on packages/analytics-service/src/datasource/matomoAPI.ts
> +// http://matamo-rhn-support-akmohan-dev.apps.sandbox.x8i5.p1.openshiftapps.com/index.php?date=2022-08-29&module=API&format=json&method=SitesManager.addSite&segment=&idSite=1&period=day
Removed. It was for a reference my bad

2022-10-10 04:17 UTC, akhilmhdh commented on packages/analytics-service/src/app.ts
> +    userBehavoirResolver,
Changed

2022-10-10 04:17 UTC, akhilmhdh commented on packages/analytics-service/src/app.ts
> +  typeDefs: [analyticConfigSchema, crashlyticsSchema, userBehavoirSchema],
Changed

2022-10-10 04:17 UTC, akhilmhdh commented on packages/analytics-service/src/app.ts
> +import { userBehavoirResolver } from './graph/matomo/resolver';
Changed

2022-10-10 04:18 UTC, akhilmhdh commented on packages/analytics-service/src/app.ts
> +import userBehavoirSchema from './graph/matomo/typedef.graphql';
Changed

2022-10-10 09:01 UTC, riginoommen commented on packages/analytics-service/.env.example
> +# SENTRTY_API_TEAM=
```suggestion
# SENTRY_API_TEAM=
```

2022-10-10 09:04 UTC, riginoommen commented on packages/analytics-service/src/graph/errors.ts
> +export const ErrUnauthorizedAccess = new Error('Unauthorized access');
Use apollo server errors

https://www.apollographql.com/docs/apollo-server/data/errors/#forbidden

2022-10-14 05:16 UTC, riginoommen requested changes

2022-10-14 05:16 UTC, riginoommen commented on packages/analytics-service/.env.example
> +# SENTRTY_API_TEAM=
```suggestion
# SENTRY_API_TEAM=
```

2022-10-14 05:37 UTC, akhilmhdh commented on packages/analytics-service/.env.example
> +# SENTRTY_API_TEAM=
Done

2022-10-14 05:38 UTC, akhilmhdh commented on packages/analytics-service/src/graph/errors.ts
> +export const ErrUnauthorizedAccess = new Error('Unauthorized access');
Done

2022-10-14 05:38 UTC, akhilmhdh commented on packages/analytics-service/.env.example
> +# SENTRTY_API_TEAM=
Done

2022-10-14 06:39 UTC, riginoommen requested changes

2022-10-14 06:39 UTC, riginoommen commented on packages/analytics-service/src/graph/errors.ts
> +export const ErrUnauthorizedAccess = new GraphQLError('Unautorized access', {
```suggestion
export const ErrUnauthorizedAccess = new GraphQLError('Unauthorized access', {
```

2022-10-14 06:44 UTC, riginoommen approved these changes

2022-10-17 07:16 UTC, hybridx approved these changes

2022-10-17 07:16 UTC, merged