fix(2010,2011): developer console v2 lighthouse modal issues fixed
1-Platform/one-platform pull request #1668
Opened 2022-11-29 12:18 UTC by akhilmhdh

# Fixes

1. 2010
2. 2011

# Explain the feature/fix

1. Resolved broken link in lighthouse config in dev console
2. Avoid on branch select spa config creation
3. Added loader for form submission

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demoed and the design review approved?

2022-11-29 12:20 UTC, riginoommen requested changes

2022-11-29 12:20 UTC, riginoommen commented on packages/developer-console-spa/src/common/components/NewProjectForm/index.tsx
> +  const { control, handleSubmit, formState: { errors, isValid,isSubmitting }, reset } = useForm<IProjectInput>( {
```suggestion
  const { control, handleSubmit, formState: { errors, isValid, isSubmitting }, reset } = useForm<IProjectInput>( {
```

2022-11-29 13:30 UTC, deshmukhmayur submitted a review, later dismissed
Other than @riginoommen's comment, everything else looks good to me.

2022-11-29 15:48 UTC, riginoommen approved these changes

2022-11-30 07:06 UTC, deshmukhmayur approved these changes

2022-11-30 07:07 UTC, deshmukhmayur commented
> @deshmukhmayur i ran vscode based eslint that takes up from nodemodules.
> 
> But we need to add eslint script into this and also may be better ones like airbnb

There's already an eslint at the root though. Do we need a separate one inside the package?

2022-11-30 07:08 UTC, merged