chore(ci-lighthouse) - Add lighthouse support in CI
1-Platform/one-platform pull request #1672
Opened 2022-12-01 08:39 UTC by hybridx

# Explain the feature/fix

-  Added lighthouse job in pipeline

## Does this PR introduce a breaking change

- No

## Screenshots

- N/A

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demoed and the design review approved?

2022-12-01 08:46 UTC, riginoommen requested changes

2022-12-01 08:46 UTC, riginoommen commented on .github/workflows/auto-deployments.yml
> +          SSI_USERNAME: ${{ secrets.SSO_USERNAME }}
```suggestion
          SSO_USERNAME: ${{ secrets.SSO_USERNAME }}
```

2022-12-01 09:28 UTC, riginoommen requested changes

2022-12-01 09:28 UTC, riginoommen commented on .github/workflows/manual-deployment.yml
> +          npx @lhci/cli@0.8.2 autorun --upload.serverBaseUrl=${{ secrets.SERVER_BASE_URL }} --upload.token=${{ secrets.LIGHTHOUSE_TOKEN }} || echo 'Lighthouse assert failed'
```suggestion
          npx @lhci/cli@0.10.0 autorun --upload.serverBaseUrl=${{ secrets.SERVER_BASE_URL }} --upload.token=${{ secrets.LIGHTHOUSE_TOKEN }} || echo 'Lighthouse assert failed'
```

2022-12-12 06:28 UTC, hybridx commented on .github/workflows/auto-deployments.yml
> +          SSI_USERNAME: ${{ secrets.SSO_USERNAME }}
Thank you, updated

2022-12-12 06:50 UTC, deshmukhmayur approved these changes
@hybridx Can you rebase and clean up the commits? Other than that, looks good to merge.

2022-12-12 06:57 UTC, hybridx commented
> @hybridx Can you rebase and clean up the commits? Other than that, looks good to merge.

Updated the commit, thanks

2022-12-12 08:34 UTC, merged