fix(2364, 2368, 2363): resolved api-catalog-spa minor bugs and typos
1-Platform/one-platform pull request #1690
Opened 2023-01-04 05:43 UTC by akhilmhdh

# Resolves

1. 2364
2. 2368
3. 2363

# Explain the feature/fix

1. Fixed filtering of service account in schema page
2. Changed placeholder of api schema 

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demoed and the design review approved?

2023-01-04 05:44 UTC, riginoommen approved these changes

2023-01-04 06:15 UTC, deshmukhmayur requested changes

2023-01-04 06:15 UTC, deshmukhmayur commented on packages/api-catalog-spa/src/pages/APICUDPage/components/APIBasicDetailsForm/APIBasicDetailsForm.tsx
> +                      placeholder="Tell use more about your API datasource"
```suggestion
                      placeholder="Tell us more about your API datasource"
```

2023-01-04 06:33 UTC, akhilmhdh commented on packages/api-catalog-spa/src/pages/APICUDPage/components/APIBasicDetailsForm/APIBasicDetailsForm.tsx
> +                      placeholder="Tell use more about your API datasource"
Changed

2023-01-05 07:48 UTC, riginoommen approved these changes

2023-01-06 06:28 UTC, deshmukhmayur approved these changes

2023-01-06 06:28 UTC, merged