chore(doc-spa): Updating SPA deployment guide
1-Platform/one-platform pull request #1712
Opened 2023-02-17 05:53 UTC by ayushsatyam146

# Closes/Fixes/Resolves
ONEPLAT-2485
### 

# Explain the feature/fix
Updating SPA deployment guide to point to the SPA quickstart deployment guide.

## Does this PR introduce a breaking change
No

2023-02-20 07:28 UTC, deshmukhmayur approved these changes

2023-02-20 08:12 UTC, hybridx approved these changes

2023-02-27 07:31 UTC, riginoommen commented on packages/doc-spa/docs/deployment-guidelines/spa-deployment-guideline.md
> +title: SPA Deployment Guideline
```suggestion
title: SPA Deployment Guidelines
```

2023-02-27 07:32 UTC, riginoommen reviewed
Update the parent which references this document

2023-02-27 07:32 UTC, riginoommen commented on packages/doc-spa/docs/deployment-guidelines/spa-deployment-guideline.md
>  id: spa-deployment-guideline
```suggestion
id: spa-deployment-guidelines
```

2023-02-27 07:32 UTC, riginoommen requested changes
Please see comments

2023-02-27 07:45 UTC, riginoommen commented on packages/doc-spa/docs/deployment-guidelines/spa-deployment-guideline.md
>  sidebar_label: SPA Guideline
```suggestion
sidebar_label: SPA Guidelines
```

2023-02-27 07:45 UTC, riginoommen commented on packages/doc-spa/docs/deployment-guidelines/spa-deployment-guideline.md
>  slug: /deployments/spa
Update slug also

2023-02-27 11:16 UTC, riginoommen approved these changes

2023-02-27 11:17 UTC, merged