714- Included the SOLR endpoint support in the Search microservice and SPA
1-Platform/one-platform pull request #706
Opened 2020-09-18 12:19 UTC by riginoommen

# Resolves 714

### 

# Explain the feature
Added SOLR endpoint to search microservice and updated the data structure to the SPA and microservices.

## Does this PR introduce a breaking change

No

## Screenshots

NA### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2020-09-19 16:02 UTC, sayak-sarkar requested changes
@riginoommen Please go through the LGTM alerts and see if there is a better way of tackling these certificate issues.

2020-09-21 07:07 UTC, riginoommen commented
> @riginoommen Please go through the LGTM alerts and see if there is a better way of tackling these certificate issues.

HI Sayak,

Removed the reject unauthorozed code and made the exceptions in the environment variables

2020-09-21 15:09 UTC, sayak-sarkar requested changes

2020-09-21 15:09 UTC, sayak-sarkar commented on packages/search-service/.env.example
> +# NODE_TLS_REJECT_UNAUTHORIZED
```suggestion
# NODE_TLS_REJECT_UNAUTHORIZED

```

2020-09-22 05:44 UTC, ghanlohar approved these changes
Looks good to me.

2020-09-22 06:29 UTC, sayak-sarkar approved these changes

2020-09-22 06:30 UTC, sayak-sarkar commented
@riginoommen Please fix the PR's title as per the team norms doc!

2020-09-22 07:05 UTC, sayak-sarkar approved these changes

2020-09-22 07:07 UTC, merged