fix:(#4902) - Fixed the interpolation of timestamp in the search ui
1-Platform/one-platform pull request #726
Opened 2020-09-29 11:20 UTC by riginoommen

# Resolves 4902

### 

# Explain the fix
Fixed the timestamp intepolation issue on the search view. and updated the ids for the search filters

## Does this PR introduce a breaking change

No

## Screenshots
N/A

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2020-09-30 08:16 UTC, deshmukhmayur requested changes
The dates should be enclosed in parenthesis for better readability and to avoid ambiguous and unexpected effects.

2020-09-30 08:16 UTC, deshmukhmayur commented on packages/search-spa/src/app/search/search.component.html
> +            {{ result.lastModifiedDate || result.createdDate | date:'fullDate' }}
```suggestion
            {{ (result.lastModifiedDate || result.createdDate) | date:'fullDate' }}
```

2020-09-30 09:25 UTC, deshmukhmayur approved these changes

2020-10-01 07:55 UTC, ghanlohar approved these changes
Looks good to me.

2020-10-01 07:56 UTC, merged