fix(#794) - Change footer links for and other fixes for SPAs
1-Platform/one-platform pull request #795
Opened 2020-11-10 13:18 UTC by hybridx

### Resolves #794 

# Explain the feature/fix

- Changed footer JSON

## Does this PR introduce a breaking change

No

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2020-11-10 17:50 UTC, ghanlohar approved these changes
Looks good to me.

2020-11-11 07:27 UTC, riginoommen approved these changes

2020-11-11 07:34 UTC, riginoommen requested changes
For few other native SPAs like user group SPA this update seems missing

2020-11-11 08:16 UTC, hybridx commented
> For few other native SPAs like user group SPA this update seems missing

@riginoommen This is specifically for all the angular SPAs

2020-11-11 09:35 UTC, sayak-sarkar commented on packages/common/footer.json
> +                "text": "One Platform in Source",
```suggestion
                "text": "One Platform on The Source",
```

2020-11-11 09:35 UTC, sayak-sarkar approved these changes

2020-11-11 09:36 UTC, riginoommen approved these changes

2020-11-11 09:37 UTC, sayak-sarkar approved these changes

2020-11-11 09:50 UTC, merged