feat:(feedback-api-layer) - Created the API Communication Layer package for the feedback
1-Platform/one-platform pull request #870
Opened 2021-01-25 06:26 UTC by riginoommen

# Resolves 839, 865

# Explain the feature
NPM package for the One Platform which enables the feedback to talk to backend apis.

## Does this PR introduce a breaking change
Yes

Migration Path. 
1) Once this is merged Configure SPAs with new feedback package and api layer from one platform. and clean the SSI.
## Screenshots

<details>
<summary>View Screenshots</summary>

![image](https://user-images.githubusercontent.com/3840244/105668923-4eb62580-5f04-11eb-859b-b0b45686439f.png)

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2021-01-28 07:49 UTC, ghanlohar approved these changes
Rest looks good to me.

2021-01-28 07:49 UTC, ghanlohar commented on packages/feedback-api-layer/src/feedback.js
> +                (window.OpNotification) ? window.OpNotification.success({ subject: `Submitted Feedback` }) : alert('Submitted Feedback')
```suggestion
                (window.OpNotification) ? window.OpNotification.success({ subject: `Your feedback has been submitted successfully` }) : alert('Your feedback has been submitted successfully')
```

2021-02-04 07:49 UTC, deshmukhmayur requested changes
This was supposed to go in the ssi-service package.

Also create a html file similar to `feedback.slim.html` that will take care of adding the script in the DOM. That will allow anyone to add this script to their app by just adding an SSI include script.

I think this needs to be improved a lot, but due to limited resources right now, just move it inside ssi, and make the changes mentioned to use it for the dependent apps.

We will have to come back to this later.

2021-02-04 11:28 UTC, riginoommen commented
The goal of this layer is to seperate the feedback dependencies as seperate one once this is approved this will be published as seperate github package. As this is an opensource project we need to provide the plug in support for everything that we uses. as from web component this will be the medium of sending the data to backend.

2021-02-05 10:01 UTC, ghanlohar approved these changes

2021-02-09 05:37 UTC, deshmukhmayur requested changes
Is this PR ready for review? As per our last discussion, some changes were pending due to another PR in op-component-library, is it still being worked on?

2021-02-09 05:37 UTC, deshmukhmayur commented on packages/feedback-api-layer/src/feedback.js
> +module.exports.sendFeedback = this.sendFeedback;
```suggestion
module.exports.sendFeedback = this.sendFeedback;

```

2021-02-09 05:37 UTC, deshmukhmayur commented on packages/feedback-api-layer/test/feedback.test.ts
> +});
```suggestion
});

```

2021-02-09 05:37 UTC, deshmukhmayur commented on packages/feedback-api-layer/webpack.config.js
> +};
```suggestion
};

```

2021-02-09 05:37 UTC, deshmukhmayur commented on packages/feedback-api-layer/jest.config.js
> +};
```suggestion
};

```

2021-02-18 02:34 UTC, closed without merging