949 - Included the cron to parse the data endpoints and to push it to solr.
1-Platform/one-platform pull request #879
Opened 2021-02-11 18:51 UTC by riginoommen

# Resolves 949

### 

# Explain the feature
Support to read the config on mapping fields from search response and push to solr. 

- APIs to manage mapping configuration
- Cron to pull data and manipulate it as per the preferences
- Push the data to the solr.

## Does this PR introduce a breaking change
Yes

## Screenshots
N/A

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2021-02-17 06:00 UTC, riginoommen commented
You can still do a code-review for this PR. Because i made this as a draft PR because needs some more testing

2021-02-22 10:39 UTC, deshmukhmayur requested changes

2021-02-22 10:39 UTC, deshmukhmayur commented on packages/search-service/service.ts
> +});
```suggestion
});

```

2021-02-22 10:39 UTC, deshmukhmayur commented on packages/search-service/src/search-mapping/cron.ts
> +}
```suggestion
}

```

2021-02-22 10:39 UTC, deshmukhmayur commented on packages/search-service/src/types.d.ts
> +}
```suggestion
}

```

2021-02-22 10:39 UTC, deshmukhmayur commented on packages/search-service/src/search-mapping/typedef.graphql
> +}
```suggestion
}

```

2021-02-22 10:39 UTC, deshmukhmayur commented on packages/search-service/src/search-mapping/helpers.ts
> +        headers.append(`Authorization`, `${process.env.GATEWAY_AUTH_TOKEN}`);
You cannot use the Gateway Auth token here, the Gateway Auth toke only works for One Platform API Gateway. the user can have their APIs hosted outside the API Gateway, so we need to get the Authorization Header value from the user and store it in the config.

2021-02-22 10:39 UTC, deshmukhmayur commented on packages/search-service/src/search-mapping/schema.ts
> +  name: String,
Add another field for SPA. That should store the reference to the SPA id from the Apps/Home Service.
```suggestion
  name: String,
  spa: { type: String, },
```

2021-02-22 10:39 UTC, deshmukhmayur commented on packages/search-service/src/search-mapping/schema.ts
> +    gqlQuery: String
Add support for user defined Authorization header, and other custom headers if their API has some special header requirements to function properly.

Also make the necessary changes in the helper functions.
```suggestion
    gqlQuery: String,
    authorizationHeader: { type: String, },
    customHeaders: [{ key: String, value: String, }],
```

2021-02-22 10:39 UTC, deshmukhmayur commented on packages/search-service/src/search-mapping/schema.ts
> +    model: { type: String, enum: ['GRAPHQL', 'REST'] },
Can you make this more generic?

i.e. No need to ask for GraphQL / ReST. Just ask for request method (GET / POST), and the request body if POST is selected. A GraphQL request is essentially a POST request with a JSON body, so the graphql query can also be provided as `body`.

2021-02-22 10:39 UTC, deshmukhmayur commented on packages/search-service/src/search-mapping/schema.ts
> +    model: { type: String, enum: ['GRAPHQL', 'REST'] },
We can simplify it further on the UI using a Postman-like UI for GraphQL requests, while storing it as a normal POST request in the backend.

2021-03-08 13:12 UTC, deshmukhmayur approved these changes

2021-03-09 05:54 UTC, deshmukhmayur requested changes

2021-03-09 05:54 UTC, deshmukhmayur commented on packages/search-service/src/search-mapping/helpers.ts
> +        return fetch(`http://api-gateway:8080/graphql`, {
This should use the environment variable. Don't hard code the urls, even for local testing.
```suggestion
        return fetch(process.env.API_GATEWAY, {
```

2021-03-09 06:06 UTC, deshmukhmayur requested changes

2021-03-09 06:06 UTC, deshmukhmayur commented on packages/search-service/src/search-mapping/helpers.ts
> +        return fetch( `${ process.env.GATEWAY_AUTH_TOKEN }`, {
```suggestion
        headers.append( `Authorization`, `${ process.env.GATEWAY_AUTH_TOKEN }` );
        headers.append( `Content-Type`, `application/json` );
        return fetch( `${ process.env.API_GATEWAY }`, {
```

2021-03-09 06:53 UTC, riginoommen commented on packages/search-service/src/search-mapping/helpers.ts
> +        return fetch( `${ process.env.GATEWAY_AUTH_TOKEN }`, {
Updated

2021-03-09 07:22 UTC, deshmukhmayur approved these changes

2021-03-09 09:10 UTC, ghanlohar approved these changes
Looks good to me.

2021-03-09 09:11 UTC, merged