Included the Feedback Webcomponent with the SSI
1-Platform/one-platform pull request #893
Opened 2021-03-01 07:34 UTC by riginoommen

# Resolves

### 

# Explain the feature
Included the feedback component with the SSI of One Platform

## Does this PR introduce a breaking change

Yes
## Screenshots
N/A

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2021-03-01 07:35 UTC, riginoommen commented
THis is a draft PR for the code review communication with @deshmukhmayur. I will update the template accordingly

2021-03-02 14:35 UTC, deshmukhmayur requested changes

2021-03-02 14:35 UTC, deshmukhmayur commented on packages/ssi-service/src/default.html
> +    } );
Do not use document.write for adding html elements in the DOM. You can create the element using document.createElement and add it to the DOM using append or prepend.
```suggestion
    const opcFeedback = document.createElement('opc-feedback');
    opFeedback.on('opc-feedback:submit', 
    opFeedback.on('opc-feedback:submit', (event) => {
      event.detail.data.createdBy = window.OpAuthHelper?.getUserInfo()?.rhatUUID;
      window.sendFeedback( event.detail.data);
    } );
```

2021-03-02 14:35 UTC, deshmukhmayur commented on packages/ssi-service/src/default.html
>          document.body.prepend( opfNav );
```suggestion
        document.body.prepend( opfNav );
        document.body.append( opcFeedback );
```

2021-03-02 14:35 UTC, deshmukhmayur commented on packages/ssi-service/src/feedback-panel/api.js
> +module.exports.sendFeedback = this.sendFeedback;
```suggestion
module.exports.sendFeedback = sendFeedback;

```

2021-03-02 14:35 UTC, deshmukhmayur commented on packages/ssi-service/src/feedback-panel/api.js
> +    let xhr = new XMLHttpRequest();
Can you replace this with a simple javascript fetch function?

Lookup [javascript fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), xhr is very outdated and you don't have to construct an xhr object just to send a simple POST request.

2021-03-03 10:10 UTC, deshmukhmayur requested changes

2021-03-03 10:10 UTC, deshmukhmayur commented on packages/ssi-service/src/feedback-panel/api.js
> +            'Authorization': `${(window.OpAuthHelper.jwtToken) ? `Bearer ${window.OpAuthHelper.jwtToken}` : null}`
```suggestion
            'Authorization': `${(window.OpAuthHelper?.jwtToken) ? `Bearer ${window.OpAuthHelper.jwtToken}` : null}`
```

2021-03-03 10:10 UTC, deshmukhmayur commented on packages/ssi-service/src/feedback-panel/api.js
> +module.exports.sendFeedback = sendFeedback;
Newline at the end of a file.
```suggestion
module.exports.sendFeedback = sendFeedback;

```

2021-03-04 10:20 UTC, deshmukhmayur approved these changes
LGTM.

2021-03-04 10:24 UTC, ghanlohar approved these changes

2021-03-04 10:24 UTC, ghanlohar approved these changes
Resolve the conflicts before merging.

2021-03-04 13:03 UTC, merged