Feat - Feb blog: Updated OKR description.
1-Platform/one-platform pull request #912
Opened 2021-03-16 12:19 UTC by ghanlohar

# Closes/Fixes/Resolves
N/A

# Explain the feature/fix
Updates February State of One Platform blog post.

## Does this PR introduce a breaking change
No

### Ready-for-merge Checklist
- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?

2021-03-16 12:21 UTC, riginoommen commented on packages/documentation-spa/blog/2021-03-10-state-of-one-platform-feb-2021.md
> +<li>Plans for usin<a href="http://quay.io/">g quay.</a><span style="text-decoration:underline;">io</span> for storing docker images for native microservices.
```suggestion
<li>Plans for using<a href="http://quay.io/">quay.</a><span style="text-decoration:underline;">io</span> for storing docker images for native microservices.
```

2021-03-16 12:24 UTC, riginoommen requested changes
neeed to correct links

2021-03-16 12:37 UTC, ghanlohar commented on packages/documentation-spa/blog/2021-03-10-state-of-one-platform-feb-2021.md
> +<li>Plans for usin<a href="http://quay.io/">g quay.</a><span style="text-decoration:underline;">io</span> for storing docker images for native microservices.
Done

2021-03-16 13:06 UTC, riginoommen approved these changes

2021-03-17 05:04 UTC, deshmukhmayur approved these changes

2021-03-17 06:55 UTC, merged