fix(#956) - Add a getting-started guide for One Platform in doc SPA
1-Platform/one-platform pull request #957
Opened 2021-05-21 09:52 UTC by hybridx

### 

# Explain the feature/fix

- Added getting started guide for One Platform

## Does this PR introduce a breaking change

No

## Screenshots

<img width="1674" alt="Screenshot 2021-05-21 at 3 20 24 PM" src="https://user-images.githubusercontent.com/12994292/119118843-42704e00-ba48-11eb-9072-35a8e7b6f56f.png">
<img width="1672" alt="Screenshot 2021-05-21 at 3 20 33 PM" src="https://user-images.githubusercontent.com/12994292/119118864-469c6b80-ba48-11eb-84e2-452835583c1d.png">

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2021-05-21 11:03 UTC, riginoommen requested changes

2021-05-21 11:03 UTC, riginoommen commented on packages/documentation-spa/docs/getting-started/get-started.md
> +title: Getting Started with One Platform
```suggestion
title: Getting Started with Component Library
```

2021-05-21 11:05 UTC, riginoommen approved these changes

2021-05-24 07:31 UTC, gisumit approved these changes

2021-05-24 07:32 UTC, merged