Feat(e2e):ONEPLAT-1079-Write test cases for User Groups.
1-Platform/one-platform pull request #986
Opened 2021-06-09 11:16 UTC by supriyagawade

# Closes/Fixes/Resolves

### 

# Explain the feature/fix

Added e2e tests for User Groups

## Does this PR introduce a breaking change
No

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2021-06-09 11:24 UTC, gautamkrishnar commented
hi @supriyagawade i noticed you putting `Cypress.config( 'includeShadowDom', true );` in almost every test spec files. I guess adding `includeShadowDom` to [cypress.json](https://github.com/1-Platform/one-platform/blob/master/cypress.json) would be a better option to do this rather than enabling it individually for reach test specs.

2021-06-09 11:26 UTC, ghanlohar requested changes

2021-06-09 11:26 UTC, ghanlohar commented on e2e/integration/usergrouptests.js
> +    /*it( 'Test for edit the group', () => {
Remove commented code.

2021-06-09 11:39 UTC, ghanlohar reviewed
@supriyagawade Can you also check the file names for consistency.

2021-06-09 11:52 UTC, riginoommen approved these changes

2021-06-09 11:59 UTC, gautamkrishnar approved these changes
Apart from @ghanlohar's comments, rest LGTM.

2021-06-11 11:40 UTC, ghanlohar approved these changes
Looks good to me.

2021-06-11 11:41 UTC, merged