feat:e2e- Fixed Home tests according to the UI changes
1-Platform/one-platform pull request #996
Opened 2021-06-18 13:52 UTC by supriyagawade

# Closes/Fixes/Resolves

### 

# Explain the feature/fix
Fixed Home tests according to the UI changes

## Does this PR introduce a breaking change
No

## Screenshots

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2021-06-18 14:18 UTC, deshmukhmayur approved these changes

2021-06-18 18:45 UTC, riginoommen requested changes

2021-06-18 18:45 UTC, riginoommen commented on e2e/helper/apps.list.js
>  export const builtapps = [
```suggestion
 export const inBuiltApps = [
```

2021-06-18 18:45 UTC, riginoommen commented on e2e/helper/apps.list.js
>  export const hostedapps = [
```suggestion
 export const hostedApps = [
```

2021-06-21 11:43 UTC, deshmukhmayur approved these changes

2021-06-23 07:08 UTC, riginoommen approved these changes

2021-06-23 07:08 UTC, riginoommen commented
@supriyagawade can you please rebase the branch and push it rest all changes looks good to me.

2021-06-23 12:07 UTC, deshmukhmayur approved these changes

2021-06-23 18:19 UTC, riginoommen commented
@supriyagawade can you please squash the commits

2021-06-24 08:13 UTC, riginoommen commented
@supriyagawade Please do fix the conflicts also

2021-06-24 09:59 UTC, riginoommen approved these changes

2021-06-24 10:08 UTC, merged